In [1]:
import numpy as np

Notes:
- `np.save()`, `np.load()` are recommended, because of platform independent;
- `ndarray.tofile()`, `np.fromfile()` not recommended, no **byteorder** or **dtype** information is saved

In [2]:
x = np.arange(10)

### `np.save()` & `np.load()`

In [3]:
# np.save: save an array to a binary .npy file
np.save('temp.npy', x)

In [4]:
# np.load: load arrays from .npz, .npy file
np.load('temp.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### `ndarray.tofile()` & `np.fromfile()`

In [5]:
x.tofile('temp1.dat') # to binary file
x.tofile('temp2.txt', sep=',') # to text file

In [6]:
np.fromfile('temp1.dat', dtype='int')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.fromfile('temp2.txt', sep=',', dtype='int')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### `np.loadtxt()` & `np.genfromtxt()`

In [8]:
np.loadtxt('temp2.txt', dtype='int', delimiter=',')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.genfromtxt('temp2.txt', dtype='int', delimiter=',')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### `np.gefromtxt()` vs `pandas.read_csv()`

Notes: for `.csv`, `pandas.read_csv()` is recommended, `np.genfromtxt()` not recommended.

In [10]:
np.genfromtxt('data.csv', delimiter=',')

array([[ nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan],
       [ nan,  nan,  nan,  nan,  nan,  5. ,  0.5,  0.5,  0. ,  0. ,  6. ],
       [ nan,  nan,  nan,  nan,  nan, 13.5,  0.5,  0.5,  2.8,  0. , 17.3],
       [ nan,  nan,  nan,  nan,  nan,  7.5,  0.5,  0.5,  0. ,  0. ,  8.5],
       [ nan,  nan,  nan,  nan,  nan,  2.5,  0.5,  0.5,  0. ,  0. ,  3.5],
       [ nan,  nan,  nan,  nan,  nan,  6.5,  0.5,  0.5,  0. ,  0. ,  7.5]])

In [11]:
import pandas as pd

In [12]:
data=pd.read_csv('data.csv')

In [13]:
data

medallion                      hack_license  \
0  76942C3205E17D7E7FE5A9F709D16434  25BA06A87905667AA1FE5990E33F0E2E   
1  517C6B330DBB3F055D007B07512628B3  2C19FBEE1A6E05612EFE4C958C14BC7F   
2  ED15611F168E41B33619C83D900FE266  754AEBD7C80DA17BA1D81D89FB6F4D1D   
3  B33E704CC189E80C9671230C16527BBC  6789C77E1CBDC850C450D72204702976   
4  BD5CC6A22D05EB2D5C8235526A2A4276  5E8F2C93B5220A922699FEBAFC2F7A54   

  vendor_id      pickup_datetime payment_type  fare_amount  surcharge  \
0       VTS  2013-01-01 00:00:00          CSH          5.0        0.5   
1       VTS  2013-01-01 00:05:00          CRD         13.5        0.5   
2       CMT  2013-01-01 00:05:52          CSH          7.5        0.5   
3       VTS  2013-01-01 00:06:00          CSH          2.5        0.5   
4       VTS  2013-01-01 00:06:00          CSH          6.5        0.5   

   mta_tax  tip_amount  tolls_amount  total_amount  
0      0.5         0.0           0.0           6.0  
1      0.5         2.8           0.0          17.3  
2      0.5         0.0           0.0           8.5  
3      0.5         0.0           0.0           3.5  
4      0.5         0.0           0.0           7.5

In [14]:
data.values

array([['76942C3205E17D7E7FE5A9F709D16434',
        '25BA06A87905667AA1FE5990E33F0E2E', 'VTS', '2013-01-01 00:00:00',
        'CSH', 5.0, 0.5, 0.5, 0.0, 0.0, 6.0],
       ['517C6B330DBB3F055D007B07512628B3',
        '2C19FBEE1A6E05612EFE4C958C14BC7F', 'VTS', '2013-01-01 00:05:00',
        'CRD', 13.5, 0.5, 0.5, 2.8, 0.0, 17.3],
       ['ED15611F168E41B33619C83D900FE266',
        '754AEBD7C80DA17BA1D81D89FB6F4D1D', 'CMT', '2013-01-01 00:05:52',
        'CSH', 7.5, 0.5, 0.5, 0.0, 0.0, 8.5],
       ['B33E704CC189E80C9671230C16527BBC',
        '6789C77E1CBDC850C450D72204702976', 'VTS', '2013-01-01 00:06:00',
        'CSH', 2.5, 0.5, 0.5, 0.0, 0.0, 3.5],
       ['BD5CC6A22D05EB2D5C8235526A2A4276',
        '5E8F2C93B5220A922699FEBAFC2F7A54', 'VTS', '2013-01-01 00:06:00',
        'CSH', 6.5, 0.5, 0.5, 0.0, 0.0, 7.5]], dtype=object)

In [15]:
data.fare_amount.values

array([ 5. , 13.5,  7.5,  2.5,  6.5])

In [16]:
data[['fare_amount', 'tip_amount']].values

array([[ 5. ,  0. ],
       [13.5,  2.8],
       [ 7.5,  0. ],
       [ 2.5,  0. ],
       [ 6.5,  0. ]])