In [1]:
import numpy as np

In [2]:
mat1=np.arange(1,21).reshape(2,-1)
arr1=mat1[0,:]
arr2=mat1[1,:]

In [3]:
# 直接将行分开
arr3, arr4=mat1

In [4]:
arr3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
arr4

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [6]:
condition1=(3<arr1) & (arr1<7)
condition1

array([False, False, False,  True,  True,  True, False, False, False,
       False])

In [7]:
# 统计True的个数
condition1.sum()

3

In [8]:
condition2=(14<arr2) & (arr2<17)
condition2

array([False, False, False, False,  True,  True, False, False, False,
       False])

In [9]:
condition2.sum()

2

In [10]:
condition_all=condition1 & condition2
condition_all

array([False, False, False, False,  True,  True, False, False, False,
       False])

In [11]:
condition_all.sum()

2

In [12]:
# 获取True的的位置: 第4, 5个为True
np.nonzero(condition_all)[0]

array([4, 5], dtype=int64)